title: Narendhiran Vijayakumar
email: narendhiranv.nitt@gmail.com
description: >-
  Robotics researcher focused on embodied AI, task and motion planning, and dependable autonomy.
baseurl: ""
url: "https://narendhiranv04.github.io"
theme: jekyll-theme-minimal
plugins:
  - jekyll-seo-tag
permalink: pretty
collections:
  posts:
    output: false
markdown: kramdown
